### ISSUE TITLE
Assignment 2 - Colormap

### ISSUE THREAD

**Issue by luisortizuriarte** [kmbarragan/clim680_project#4]
This is a great start. 

I noticed in your code that you are specifying the colormap and normalization. This is great, because you're making sure all your plots have the same mapping. However, I think your choices in the centeral and intervals in the mapping could be improved. If you're trying to show the geopotential height low over Greenland/the northern edge of your domain, you might want to specify a colormap that assigns more intense colors to those values. Perhaps you could narrow the range of values or move the center of the norm to the left?

**Comment by kmbarragan** [comment]
Hello Dr. Ortiz,
I updated the code by changing the center of the colorbar and the cmap color

**Comment by luisortizuriarte** [comment]
Great! Closing.
